spring:
    application:
        name: StrideChatBot

security:
  oauth2:
    client:
      clientId: GPvwrGWgxPG08OuFs5CUtPAXn0Lr1bcU
      clientSecret: krcqXOQzfFmniFZ3p-1mZNvLz0rigvalqrtbpr1TRShoEb7LYGN0fQdnMxSyf4pk
      accessTokenUri: https://api.atlassian.com/oauth/token
      userAuthorizationUri: https://aeece167.ngrok.io
    resource:
      userInfoUri: bugfix2